//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:DarthScottius", ConfigurationName="ISeahawks")]
public interface ISeahawks
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DarthScottius/ISeahawks/BeatTheNiners", ReplyAction="urn:DarthScottius/ISeahawks/BeatTheNinersResponse")]
    string BeatTheNiners(int pointSpread);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DarthScottius/ISeahawks/BeatTheNiners", ReplyAction="urn:DarthScottius/ISeahawks/BeatTheNinersResponse")]
    System.Threading.Tasks.Task<string> BeatTheNinersAsync(int pointSpread);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DarthScottius/ISeahawks/BeatTheBroncos", ReplyAction="urn:DarthScottius/ISeahawks/BeatTheBroncosResponse")]
    string BeatTheBroncos(int pointSpread);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DarthScottius/ISeahawks/BeatTheBroncos", ReplyAction="urn:DarthScottius/ISeahawks/BeatTheBroncosResponse")]
    System.Threading.Tasks.Task<string> BeatTheBroncosAsync(int pointSpread);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DarthScottius/ISeahawks/WinSuperbowl", ReplyAction="urn:DarthScottius/ISeahawks/WinSuperbowlResponse")]
    string WinSuperbowl();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DarthScottius/ISeahawks/WinSuperbowl", ReplyAction="urn:DarthScottius/ISeahawks/WinSuperbowlResponse")]
    System.Threading.Tasks.Task<string> WinSuperbowlAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISeahawksChannel : ISeahawks, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SeahawksClient : System.ServiceModel.ClientBase<ISeahawks>, ISeahawks
{
    
    public SeahawksClient()
    {
    }
    
    public SeahawksClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SeahawksClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SeahawksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SeahawksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string BeatTheNiners(int pointSpread)
    {
        return base.Channel.BeatTheNiners(pointSpread);
    }
    
    public System.Threading.Tasks.Task<string> BeatTheNinersAsync(int pointSpread)
    {
        return base.Channel.BeatTheNinersAsync(pointSpread);
    }
    
    public string BeatTheBroncos(int pointSpread)
    {
        return base.Channel.BeatTheBroncos(pointSpread);
    }
    
    public System.Threading.Tasks.Task<string> BeatTheBroncosAsync(int pointSpread)
    {
        return base.Channel.BeatTheBroncosAsync(pointSpread);
    }
    
    public string WinSuperbowl()
    {
        return base.Channel.WinSuperbowl();
    }
    
    public System.Threading.Tasks.Task<string> WinSuperbowlAsync()
    {
        return base.Channel.WinSuperbowlAsync();
    }
}
